# syntax = docker/dockerfile:1

# Adjust NODE_VERSION as desired
ARG NODE_VERSION=20.18.0
FROM node:${NODE_VERSION}-slim AS base

LABEL fly_launch_runtime="Node.js"

# Node.js app lives here
WORKDIR /app

# Set production environment
ENV NODE_ENV="production"

# Install pnpm
# Pin to pnpm 10.x to match lockfileVersion 9.0 (generated by pnpm 10.24.0)
ARG PNPM_VERSION=10.0.0
ARG NPM_STRICT_SSL=true
RUN npm config set strict-ssl $NPM_STRICT_SSL && \
    npm install -g pnpm@$PNPM_VERSION

# Set CI environment variable to avoid pnpm TTY issues
ENV CI=true

# Throw-away build stage to reduce size of final image
FROM base AS build

# Install packages needed to build node modules
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential node-gyp pkg-config python-is-python3

# Copy application code (includes workspace package.json files and pre-built casino-data-api dist)
COPY . .

# Install node modules
ARG NPM_STRICT_SSL=true
ENV PUPPETEER_SKIP_DOWNLOAD=true
RUN npm config set strict-ssl $NPM_STRICT_SSL && \
    pnpm config set strict-ssl $NPM_STRICT_SSL && \
    pnpm install --frozen-lockfile --prod=false

# Build application
RUN pnpm run build

# Remove development dependencies
RUN pnpm prune --prod


# Final stage for app image
FROM base

# Install nginx, supervisor, and wget for multi-process management and health checks
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y nginx supervisor wget && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /var/log/supervisor

# Copy built application
COPY --from=build /app /app

# Copy nginx config for unified container
COPY services/reverse-proxy/nginx.render.conf /etc/nginx/nginx.conf

# Copy supervisor config
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Expose port 8080 (Hyperlift default)
EXPOSE 8080

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
    CMD wget --quiet --tries=1 --spider http://localhost:8080/proxy-health || exit 1

# Start supervisor (manages nginx + node services)
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
