// @ts-check

const config = {
  title: 'TiltCheck Docs',
  tagline: 'Provable Fairness & Trust Engine',
  url: 'https://tiltcheck.it.com',
  baseUrl: '/',
  favicon: 'img/favicon.ico',
  organizationName: 'tiltcheck',
  projectName: 'docs',
  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',
  i18n: { defaultLocale: 'en', locales: ['en'] },
  presets: [
    [
      'classic',
      ({
        docs: {
          path: 'docs',
          routeBasePath: 'docs',
          // Use autogenerated sidebar
          sidebarPath: require.resolve('./sidebars.js'),
          editCurrentVersion: false
        },
        blog: false,
        theme: { customCss: require.resolve('./src/css/custom.css') }
      })
    ]
  ],
  plugins: [
    [
      'docusaurus-plugin-openapi-docs',
      {
        id: 'openapi',
        docsPluginId: 'classic',
        config: {
          tiltcheck: {
            specPath: 'static/openapi/tiltcheck.yaml',
            outputDir: 'api/tiltcheck',
            sidebarOptions: { groupPathsBy: 'tag' },
            label: 'TiltCheck Core'
          },
          trust: {
            specPath: 'static/openapi/trust.yaml',
            outputDir: 'api/trust',
            sidebarOptions: { groupPathsBy: 'tag' },
            label: 'Trust Engine'
          }
        }
      }
    ]
  ],
  themeConfig: {
    navbar: {
      title: 'TiltCheck',
      items: [
        { to: '/docs/0-intro', label: 'Docs', position: 'left' },
        { to: '/docs/api/tiltcheck', label: 'API', position: 'left' },
        { to: '/docs/api/trust', label: 'Trust API', position: 'left' },
        { href: 'https://github.com/jmenichole/tiltcheck-monorepo', label: 'GitHub', position: 'right' }
      ]
    },
    algolia: {
      appId: process.env.ALGOLIA_APP_ID || 'APP_ID',
      apiKey: process.env.ALGOLIA_SEARCH_KEY || 'SEARCH_KEY', // search-only key
      indexName: process.env.ALGOLIA_INDEX_NAME || 'tiltcheck_docs',
      contextualSearch: true
    },
    footer: {
      style: 'dark',
      copyright: `© ${new Date().getFullYear()} TiltCheck`
    }
  }
};

module.exports = config;
