---
name: Security Vulnerability
about: Report a security issue (ONLY use for non-critical issues - email for critical)
title: '[SECURITY] '
labels: ['security', 'needs-triage']
assignees: ['jmenichole']
---

⚠️ **CRITICAL VULNERABILITIES**
If this is a critical security vulnerability (e.g., wallet exploit, data breach, authentication bypass), 
**DO NOT** file a public issue. Email: jmenichole.security@proton.me

---

## Vulnerability Type
<!-- Select the type of vulnerability -->
- [ ] Dependency vulnerability
- [ ] Code vulnerability (low severity)
- [ ] Configuration issue
- [ ] Documentation gap
- [ ] Best practice violation
- [ ] Other: ___________

## Affected Component
<!-- Which part of the system is affected? -->

## Severity Assessment
<!-- Your assessment of severity -->
- [ ] Low - Minor security improvement
- [ ] Medium - Potential issue under specific conditions
- [ ] High - Should use private disclosure (email instead)
- [ ] Critical - MUST use private disclosure (email instead)

## Description
<!-- Description of the vulnerability -->

## Reproduction Steps
<!-- If applicable, steps to reproduce (for low severity issues only) -->

## Suggested Fix
<!-- If you have a suggestion for how to fix this -->

## References
<!-- Links to CVEs, advisories, or related issues -->

---

**Remember:** For high/critical issues or anything involving:
- Wallet security
- Private key exposure
- Authentication bypass
- Data breaches
- Trust engine manipulation

**Email jmenichole.security@proton.me immediately** and do not file a public issue.
